name: Deploy Branch with Manual Input

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the branch name (see available options in logs)'
        required: true
        type: string

jobs:
  fetch-branches:
    runs-on: ubuntu-latest
    steps:
      - name: List all available branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching available branches..."
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/branches \
            | jq -r '.[].name'

          echo "Please enter one of the above branches when triggering the workflow."
