name: Update Deploy Workflow on Branch Events

on:
  create:
    branches: ['*']
  delete:
    branches: ['*']

permissions:
  contents: write  # Allows read/write access to repository contents, but not direct workflow updates with GITHUB_TOKEN

jobs:
  update-deploy-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (jq for JSON parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch branches and update workflow YAML
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch all branches from the GitHub API
          branches=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/branches | jq -r '.[].name')

          # Define the workflow file path
          workflow_path=".github/workflows/deploy-workflow.yml"

          # Generate the updated workflow YAML file
          echo "name: Deploy with Dynamic Branch Options" > $workflow_path
          echo "" >> $workflow_path
          echo "on:" >> $workflow_path
          echo "  workflow_dispatch:" >> $workflow_path
          echo "    inputs:" >> $workflow_path
          echo "      branch_name:" >> $workflow_path
          echo "        description: 'Select a branch to deploy'" >> $workflow_path
          echo "        required: true" >> $workflow_path
          echo "        type: choice" >> $workflow_path
          echo "        options:" >> $workflow_path

          # Add each branch to the options list
          for branch in $branches; do
            echo "          - $branch" >> $workflow_path
          done

      - name: Commit and push updated workflow to a new branch
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"
          git checkout -b update-deploy-workflow
          git add .github/workflows/deploy-workflow.yml
          git commit -m "Update deploy workflow with dynamic branch options"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git update-deploy-workflow

      - name: Create pull request
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Create a pull request using GitHub API
          curl -X POST -H "Authorization: token $PAT_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Update deploy workflow with dynamic branch options",
              "head": "update-deploy-workflow",
              "base": "main",
              "body": "This pull request updates the deploy workflow with the latest branch options."
            }'
